
//----------------------------------------------------
// The following code was generated by CUP v0.11b 20160615 (GIT 4ac7450)
//----------------------------------------------------

package analizadores;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int MENOS = 9;
  public static final int EQUAL = 14;
  public static final int DECIMAL = 18;
  public static final int DIVIDIDO = 11;
  public static final int REVALUAR = 20;
  public static final int PALABRA = 17;
  public static final int PARIZQ = 3;
  public static final int PARDER = 4;
  public static final int UMENOS = 19;
  public static final int POR = 10;
  public static final int CICLO = 22;
  public static final int COMA = 7;
  public static final int EOF = 0;
  public static final int ESCRIBIR = 21;
  public static final int SI = 15;
  public static final int error = 1;
  public static final int MIN = 13;
  public static final int CORIZQ = 5;
  public static final int ENTERO = 16;
  public static final int MAX = 12;
  public static final int CORDER = 6;
  public static final int MAS = 8;
  public static final int PTCOMA = 2;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "PTCOMA",
  "PARIZQ",
  "PARDER",
  "CORIZQ",
  "CORDER",
  "COMA",
  "MAS",
  "MENOS",
  "POR",
  "DIVIDIDO",
  "MAX",
  "MIN",
  "EQUAL",
  "SI",
  "ENTERO",
  "PALABRA",
  "DECIMAL",
  "UMENOS",
  "REVALUAR",
  "ESCRIBIR",
  "CICLO"
  };
}

